apiVersion: v1
kind: PersistentVolume
metadata:
  name: godoworkspace
spec:
  storageClassName: "nfs-storage"
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/godoworkspace  # 指定nfs的挂载点
    server: 172.23.144.11  # 指定nfs服务地址，这是我node1的主机ip
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner

