# sed.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sed-apply
spec:
  description: >-
    修改yaml文件中的镜像
  workspaces:
    - name: sedyaml-repo
  resources:
    inputs:
      - name: repo
        type: git
  params:
  - name: admin-api-image
    description: Reference of the image docker will produce.
  - name: admin-rpc-image
    description: Reference of the image docker will produce.
  - name: usercenter-api-image
    description: Reference of the image docker will produce.
  - name: usercenter-rpc-image
    description: Reference of the image docker will produce.
  - name: order-api-image
    description: Reference of the image docker will produce.
  - name: order-rpc-image
    description: Reference of the image docker will produce.
  - name: travel-api-image
    description: Reference of the image docker will produce.
  - name: travel-rpc-image
    description: Reference of the image docker will produce.
  - name: payment-api-image
    description: Reference of the image docker will produce.
  - name: payment-rpc-image
    description: Reference of the image docker will produce.
  - name: mqjob-rpc-image
    description: Reference of the image docker will produce.
  - name: mqscheduler-rpc-image
    description: Reference of the image docker will produce.
  steps:
    - name: sed
      image: bash:5.0.18
      workingDir: /workspace/repo/deploy/k8s/v1  #""
      script: |
        #!/usr/bin/env bash
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-admin-api.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-admin-rpc.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-travel-api.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-travel-rpc.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-order-api.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-order-rpc.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-usercenter-api.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-usercenter-rpc.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-payment-api.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-payment-rpc.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-mqjob-rpc.yaml
        sed -i -r 's/namespace: (.*)/namespace: default/g' go-travel-mqscheduler-rpc.yaml 
        sed -i -r 's/namespace: (.*)/namespace: default/g' admin.sa.yaml
        echo admin-api-image=$(params.admin-api-image)
        echo admin-rpc-image=$(params.admin-rpc-image)
        echo order-api-image=$(params.order-api-image)
        echo order-rpc-image=$(params.order-rpc-image)
        echo travel-api-image=$(params.travel-api-image)
        echo travel-rpc-image=$(params.travel-rpc-image)
        echo usercenter-api-image=$(params.usercenter-api-image)
        echo usercenter-rpc-image=$(params.usercenter-rpc-image)
        echo payment-api-image=$(params.payment-api-image)
        echo payment-rpc-image=$(params.payment-rpc-image)
        echo mqjob-rpc-image=$(params.mqjob-rpc-image)
        echo mqscheduler-rpc-image=$(params.mqscheduler-rpc-image)
        sed -i -r "s/image: (.*)/image: ${admin-api-image}/g" go-travel-admin-api.yaml
        sed -i -r "s/image: (.*)/image: ${admin-rpc-image}/g" go-travel-admin-rpc.yaml
        sed -i -r "s/image: (.*)/image: ${travel-api-image}/g" go-travel-travel-api.yaml
        sed -i -r "s/image: (.*)/image: ${travel-rpc-image}/g" go-travel-travel-rpc.yaml
        sed -i -r "s/image: (.*)/image: ${usercenter-api-image}/g" go-travel-usercenter-api.yaml
        sed -i -r "s/image: (.*)/image: ${usercenter-rpc-image}/g" go-travel-usercenter-rpc.yaml
        sed -i -r "s/image: (.*)/image: ${order-rpc-image}/g" go-travel-order-rpc.yaml
        sed -i -r "s/image: (.*)/image: ${order-api-image}/g" go-travel-order-api.yaml
        sed -i -r "s/image: (.*)/image: ${payment-api-image}/g" go-travel-payment-api.yaml
        sed -i -r "s/image: (.*)/image: ${payment-rpc-image}/g" go-travel-payment-rpc.yaml
        sed -i -r "s/image: (.*)/image: ${mqjob-rpc-image}/g" go-travel-mqjob-rpc.yaml
        sed -i -r "s/image: (.*)/image: ${mqscheduler-rpc-image}/g" go-travel-mqscheduler-rpc.yaml
    - name: kubectl
      image: 010101010007/cjqkubectl:v1
      workingDir: /workspace/repo/deploy/k8s/v1
      script: |
        #!/usr/bin/env bash
        kubectl apply -f admin.sa.yaml
        kubectl apply -f go-travel-admin-api.yaml
        kubectl apply -f go-travel-admin-rpc.yaml
        kubectl apply -f go-travel-travel-api.yaml
        kubectl apply -f go-travel-travel-rpc.yaml
        kubectl apply -f go-travel-order-api.yaml
        kubectl apply -f go-travel-order-rpc.yaml
        kubectl apply -f go-travel-usercenter-api.yaml
        kubectl apply -f go-travel-usercenter-rpc.yaml
        kubectl apply -f go-travel-payment-api.yaml
        kubectl apply -f go-travel-payment-rpc.yaml
        kubectl apply -f go-travel-mqjob-rpc.yaml
        kubectl apply -f go-travel-mqscheduler-rpc.yaml
      volumeMounts:
        - name: kubeconfig #将/root/.kube文件挂载进来，容器才能访问k8s集群
          mountPath: /root/.kube
  volumes:
    - name: kubeconfig
      hostPath:
        path: /root/.kube
