FROM golang:1.18.1 AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
RUN go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.cn,direct

WORKDIR /go/src

ADD go.mod .
ADD go.sum .
RUN go mod tidy
#RUN go mod download

COPY . .
COPY service/mqueue/cmd/job/etc /go/bin/etc
RUN go build -ldflags="-s -w" -o /go/bin/mqueue service/mqueue/cmd/job/mqueue.go


FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ Asia/Shanghai

WORKDIR /app
#COPY --from=builder /app/admin /app/admin
#COPY --from=builder /app/etc /app/etc
COPY --from=builder /go/bin .

CMD ["./mqueue", "-f", "etc/mqueue.yaml"]
