FROM golang:1.18.1 AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0

#ENV GOPROXY https://goproxy.cn,direct
#RUN export GO111MODULE=on && export GOPROXY=https://mirrors.aliyun.com/goproxy/

RUN go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.cn,direct


#RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
#RUN apk update --no-cache && apk add --no-cache tzdata

#WORKDIR /build

WORKDIR /go/src

ADD go.mod .
ADD go.sum .
RUN go mod tidy

#RUN go mod download

COPY . .
COPY service/admin/cmd/api/etc /go/bin/etc
RUN go build -ldflags="-s -w" -o /go/bin/admin service/admin/cmd/api/admin.go


FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ Asia/Shanghai

WORKDIR /app

#COPY --from=builder /app/admin /app/admin
#COPY --from=builder /app/etc /app/etc

COPY --from=builder /go/bin .

CMD ["./admin", "-f", "etc/admin-api.yaml"]
