FROM golang:1.18.1 AS builder

LABEL stage=gobuilder

ENV CGO_ENABLED 0
RUN go env -w GO111MODULE=on && go env -w GOPROXY=https://goproxy.cn,direct

WORKDIR /go/src

ADD go.mod .
ADD go.sum .
RUN go mod tidy
#RUN go mod download

COPY . .
COPY service/order/cmd/rpc/etc /go/bin/etc
RUN go build -ldflags="-s -w" -o /go/bin/order service/order/cmd/rpc/order.go


FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /usr/share/zoneinfo/Asia/Shanghai
ENV TZ Asia/Shanghai

WORKDIR /app
COPY --from=builder /go/bin .

CMD ["./order", "-f", "etc/order.yaml"]
