// Code generated by goctl. DO NOT EDIT!
// Source: manager.proto

package admin

import (
	"context"

	"go-travel/service/admin/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangePwdReq  = pb.ChangePwdReq
	ChangePwdResp = pb.ChangePwdResp
	LoginReq      = pb.LoginReq
	LoginResp     = pb.LoginResp
	UserInfoReq   = pb.UserInfoReq
	UserInfoResp  = pb.UserInfoResp

	Admin interface {
		AdminLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		AdminInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		ChangePwd(ctx context.Context, in *ChangePwdReq, opts ...grpc.CallOption) (*ChangePwdResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) AdminLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewAdminClient(m.cli.Conn())
	return client.AdminLogin(ctx, in, opts...)
}

func (m *defaultAdmin) AdminInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := pb.NewAdminClient(m.cli.Conn())
	return client.AdminInfo(ctx, in, opts...)
}

func (m *defaultAdmin) ChangePwd(ctx context.Context, in *ChangePwdReq, opts ...grpc.CallOption) (*ChangePwdResp, error) {
	client := pb.NewAdminClient(m.cli.Conn())
	return client.ChangePwd(ctx, in, opts...)
}
