apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  #creationTimestamp: null
  #generateName: test-run-
  #namespace: default
  name: testrun
spec:
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: demo-git
  #serviceAccountName: ""
  taskRef:
    name: test
#status:
  #podName: ""
