apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-rpc
  namespace: gozero
  labels:
    app: payment-rpc
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: payment-rpc
  template:
    metadata:
      labels:
        app: payment-rpc
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: payment-rpc
        image: harbor.k8s.local/library/gotravel-payment-rpc:v1
        ports:
        - containerPort: 2002
        readinessProbe:
          tcpSocket:
            port: 2002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2002
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 150m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: payment-rpc-svc
  namespace: gozero
  annotations:
    prometheus.io/port: "4005"
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 2002
  selector:
    app: payment-rpc

