apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter-api
  namespace: gozero
  labels:
    app: usercenter-api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: usercenter-api
  template:
    metadata:
      labels:
        app: usercenter-api
    spec:
      serviceAccountName: find-endpoints
      containers:
      - name: usercenter-api
        image: harbor.k8s.local/library/gotravel-usercenter-api:v1
        ports:
        - containerPort: 1004
        readinessProbe:
          tcpSocket:
            port: 1004
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1004
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 150m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: usercenter-api-svc
  namespace: gozero
spec:
  ports:
    - nodePort: 32105
      port: 1004
      protocol: TCP
      targetPort: 1004
  type: NodePort
  selector:
    app: usercenter-api

