// Code generated by goctl. DO NOT EDIT!
// Source: manager.proto

package server

import (
	"context"

	"go-travel/service/admin/cmd/rpc/internal/logic"
	"go-travel/service/admin/cmd/rpc/internal/svc"
	"go-travel/service/admin/cmd/rpc/pb"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) AdminLogin(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}

func (s *AdminServer) AdminInfo(ctx context.Context, in *pb.UserInfoReq) (*pb.UserInfoResp, error) {
	l := logic.NewAdminInfoLogic(ctx, s.svcCtx)
	return l.AdminInfo(in)
}

func (s *AdminServer) ChangePwd(ctx context.Context, in *pb.ChangePwdReq) (*pb.ChangePwdResp, error) {
	l := logic.NewChangePwdLogic(ctx, s.svcCtx)
	return l.ChangePwd(in)
}
