# 定义mysql的Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: gozero
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7 #mysql5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: password
          # 如果你不想使用secret对象保存mysql登录密码，可以直接使用下面的方式指定，简单粗暴未尝不可    
          #value: "123456"
        ports:
        - containerPort: 3306
        #command: [ "/bin/sh", "-c","mysql -uroot -p100.Acjq < /home/one.sql" ]
        volumeMounts:
        - name: mysqlvolume
          mountPath: /var/lib/mysql
        - name: sqlcmvolume
          mountPath: /home
      volumes:
      - name: mysqlvolume
        # 使用pvc
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: sqlcmvolume
        configMap:
          name: sql-cm
