apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-mon
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s   #抓取指标数据间隔
      scrape_timeout: 15s   #抓取超时设置，也就是一次性最多抓取15s
    scrape_configs:
    - job_name: 'prometheus'   #默认自带的自身监控
      static_configs:
      - targets: ['localhost:9090']    #抓取的对象
    alerting:
      alertmanagers:
      - static_configs:
        - targets: ["alertmanager:9093"]


