// Code generated by goctl. DO NOT EDIT!
// Source: travel.proto

package travel

import (
	"context"

	"go-travel/service/travel/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddHomestayActivityReq        = pb.AddHomestayActivityReq
	AddHomestayActivityResp       = pb.AddHomestayActivityResp
	AddHomestayBusinessReq        = pb.AddHomestayBusinessReq
	AddHomestayBusinessResp       = pb.AddHomestayBusinessResp
	AddHomestayReq                = pb.AddHomestayReq
	AddHomestayResp               = pb.AddHomestayResp
	AddHomestaycommentReq         = pb.AddHomestaycommentReq
	AddHomestaycommentResp        = pb.AddHomestaycommentResp
	DeleteHomestayActivityReq     = pb.DeleteHomestayActivityReq
	DeleteHomestayActivityResp    = pb.DeleteHomestayActivityResp
	DeleteHomestayBusinessReq     = pb.DeleteHomestayBusinessReq
	DeleteHomestayBusinessResp    = pb.DeleteHomestayBusinessResp
	DeleteHomestayReq             = pb.DeleteHomestayReq
	DeleteHomestayResp            = pb.DeleteHomestayResp
	DeleteHomestaycommentReq      = pb.DeleteHomestaycommentReq
	DeleteHomestaycommentResp     = pb.DeleteHomestaycommentResp
	Homestay                      = pb.Homestay
	HomestayDetailReq             = pb.HomestayDetailReq
	HomestayDetailResp            = pb.HomestayDetailResp
	ListHomestayAcitivityItemResp = pb.ListHomestayAcitivityItemResp
	ListHomestayActivityReq       = pb.ListHomestayActivityReq
	ListHomestayActivityResp      = pb.ListHomestayActivityResp
	ListHomestayBusinessItemResp  = pb.ListHomestayBusinessItemResp
	ListHomestayBusinessReq       = pb.ListHomestayBusinessReq
	ListHomestayBusinessResp      = pb.ListHomestayBusinessResp
	ListHomestayItemResp          = pb.ListHomestayItemResp
	ListHomestayReq               = pb.ListHomestayReq
	ListHomestayResp              = pb.ListHomestayResp
	ListHomestaycommentItemResp   = pb.ListHomestaycommentItemResp
	ListHomestaycommentReq        = pb.ListHomestaycommentReq
	ListHomestaycommentResp       = pb.ListHomestaycommentResp
	UpdateHomestayActivityReq     = pb.UpdateHomestayActivityReq
	UpdateHomestayActivityResp    = pb.UpdateHomestayActivityResp
	UpdateHomestayBusinessReq     = pb.UpdateHomestayBusinessReq
	UpdateHomestayBusinessResp    = pb.UpdateHomestayBusinessResp
	UpdateHomestayReq             = pb.UpdateHomestayReq
	UpdateHomestayResp            = pb.UpdateHomestayResp
	UpdateHomestaycommentReq      = pb.UpdateHomestaycommentReq
	UpdateHomestaycommentResp     = pb.UpdateHomestaycommentResp

	Travel interface {
		// homestayDetail
		HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error)
		// provide to admin use
		AddHomestay(ctx context.Context, in *AddHomestayReq, opts ...grpc.CallOption) (*AddHomestayResp, error)
		DeleteHomestay(ctx context.Context, in *DeleteHomestayReq, opts ...grpc.CallOption) (*DeleteHomestayResp, error)
		UpdateHomestay(ctx context.Context, in *UpdateHomestayReq, opts ...grpc.CallOption) (*UpdateHomestayResp, error)
		ListHomestay(ctx context.Context, in *ListHomestayReq, opts ...grpc.CallOption) (*ListHomestayResp, error)
		// homestayActivity
		AddHomestayActivity(ctx context.Context, in *AddHomestayActivityReq, opts ...grpc.CallOption) (*AddHomestayActivityResp, error)
		DeleteHomestatActivity(ctx context.Context, in *DeleteHomestayActivityReq, opts ...grpc.CallOption) (*DeleteHomestayResp, error)
		UpdateHomestayActivity(ctx context.Context, in *UpdateHomestayActivityReq, opts ...grpc.CallOption) (*UpdateHomestayActivityResp, error)
		ListHomestayActivity(ctx context.Context, in *ListHomestayActivityReq, opts ...grpc.CallOption) (*ListHomestayActivityResp, error)
		// homestayBusiness
		AddHomestayBusiness(ctx context.Context, in *AddHomestayBusinessReq, opts ...grpc.CallOption) (*AddHomestayActivityResp, error)
		DeleteHomestayBusiness(ctx context.Context, in *DeleteHomestayBusinessReq, opts ...grpc.CallOption) (*DeleteHomestayBusinessResp, error)
		UpdateHomestayBussiness(ctx context.Context, in *UpdateHomestayBusinessReq, opts ...grpc.CallOption) (*UpdateHomestayBusinessResp, error)
		ListHomestayBussiness(ctx context.Context, in *ListHomestayBusinessReq, opts ...grpc.CallOption) (*ListHomestayBusinessResp, error)
		// homestayComment
		ListHomestayComment(ctx context.Context, in *ListHomestaycommentReq, opts ...grpc.CallOption) (*ListHomestaycommentResp, error)
		AddHomestayComment(ctx context.Context, in *AddHomestaycommentReq, opts ...grpc.CallOption) (*AddHomestaycommentResp, error)
		DeleteHomestayComment(ctx context.Context, in *DeleteHomestaycommentReq, opts ...grpc.CallOption) (*DeleteHomestaycommentResp, error)
		UpdateHomestayComment(ctx context.Context, in *UpdateHomestaycommentReq, opts ...grpc.CallOption) (*UpdateHomestaycommentResp, error)
	}

	defaultTravel struct {
		cli zrpc.Client
	}
)

func NewTravel(cli zrpc.Client) Travel {
	return &defaultTravel{
		cli: cli,
	}
}

// homestayDetail
func (m *defaultTravel) HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.HomestayDetail(ctx, in, opts...)
}

// provide to admin use
func (m *defaultTravel) AddHomestay(ctx context.Context, in *AddHomestayReq, opts ...grpc.CallOption) (*AddHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestay(ctx, in, opts...)
}

func (m *defaultTravel) DeleteHomestay(ctx context.Context, in *DeleteHomestayReq, opts ...grpc.CallOption) (*DeleteHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DeleteHomestay(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestay(ctx context.Context, in *UpdateHomestayReq, opts ...grpc.CallOption) (*UpdateHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestay(ctx, in, opts...)
}

func (m *defaultTravel) ListHomestay(ctx context.Context, in *ListHomestayReq, opts ...grpc.CallOption) (*ListHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.ListHomestay(ctx, in, opts...)
}

// homestayActivity
func (m *defaultTravel) AddHomestayActivity(ctx context.Context, in *AddHomestayActivityReq, opts ...grpc.CallOption) (*AddHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestayActivity(ctx, in, opts...)
}

func (m *defaultTravel) DeleteHomestatActivity(ctx context.Context, in *DeleteHomestayActivityReq, opts ...grpc.CallOption) (*DeleteHomestayResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DeleteHomestatActivity(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestayActivity(ctx context.Context, in *UpdateHomestayActivityReq, opts ...grpc.CallOption) (*UpdateHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestayActivity(ctx, in, opts...)
}

func (m *defaultTravel) ListHomestayActivity(ctx context.Context, in *ListHomestayActivityReq, opts ...grpc.CallOption) (*ListHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.ListHomestayActivity(ctx, in, opts...)
}

// homestayBusiness
func (m *defaultTravel) AddHomestayBusiness(ctx context.Context, in *AddHomestayBusinessReq, opts ...grpc.CallOption) (*AddHomestayActivityResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestayBusiness(ctx, in, opts...)
}

func (m *defaultTravel) DeleteHomestayBusiness(ctx context.Context, in *DeleteHomestayBusinessReq, opts ...grpc.CallOption) (*DeleteHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DeleteHomestayBusiness(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestayBussiness(ctx context.Context, in *UpdateHomestayBusinessReq, opts ...grpc.CallOption) (*UpdateHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestayBussiness(ctx, in, opts...)
}

func (m *defaultTravel) ListHomestayBussiness(ctx context.Context, in *ListHomestayBusinessReq, opts ...grpc.CallOption) (*ListHomestayBusinessResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.ListHomestayBussiness(ctx, in, opts...)
}

// homestayComment
func (m *defaultTravel) ListHomestayComment(ctx context.Context, in *ListHomestaycommentReq, opts ...grpc.CallOption) (*ListHomestaycommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.ListHomestayComment(ctx, in, opts...)
}

func (m *defaultTravel) AddHomestayComment(ctx context.Context, in *AddHomestaycommentReq, opts ...grpc.CallOption) (*AddHomestaycommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.AddHomestayComment(ctx, in, opts...)
}

func (m *defaultTravel) DeleteHomestayComment(ctx context.Context, in *DeleteHomestaycommentReq, opts ...grpc.CallOption) (*DeleteHomestaycommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.DeleteHomestayComment(ctx, in, opts...)
}

func (m *defaultTravel) UpdateHomestayComment(ctx context.Context, in *UpdateHomestaycommentReq, opts ...grpc.CallOption) (*UpdateHomestaycommentResp, error) {
	client := pb.NewTravelClient(m.cli.Conn())
	return client.UpdateHomestayComment(ctx, in, opts...)
}
